CREATE TABLE CHAT_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(256) NOT NULL,
    RANDOM_ID BIGINT NOT NULL
);

CREATE TABLE MESSAGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SENDER BIGINT NOT NULL,
    RECEIVER BIGINT NOT NULL,
    CONTENT VARCHAR(256) NOT NULL,
    TIMES TIMESTAMP NOT NULL
);